---
title: "population-age-public Replication"
author: "Hannah Valencia"
date: "4/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(tidyverse)
```


```{r, message = FALSE, include = FALSE, cache=TRUE}
download.file("https://data.nber.org/mortality/2007/mort2007.csv.zip",
                           destfile = "mort07.zip")
unzip("mort07.zip")
mort07 <- read_csv("mort2007.csv")

mort07 <- mort07 %>%
  filter(ucod %in% c("W32", "W33", "W34")) %>%
  select(restatus, monthdth, sex, age, ager52, ager27, ager12, weekday, year, ucod, race, racer3, racer5)

file.remove("mort2007.csv")
file.remove("mort07.zip")
```

```{r, message = FALSE, include = FALSE, cache = TRUE}
download.file("https://data.nber.org/mortality/2008/mort2008.csv.zip",
                           destfile = "mort08.zip")
unzip("mort08.zip")
mort08 <- read_csv("mort2008.csv")

mort08 <- mort08 %>%
  filter(ucod %in% c("W32", "W33", "W34")) %>%
  select(restatus, monthdth, sex, age, ager52, ager27, ager12, weekday, year, ucod, race, racer3, racer5)

file.remove("mort2008.csv")
file.remove("mort08.zip")
```

```{r, message = FALSE, include = FALSE, cache = TRUE}
download.file("https://data.nber.org/mortality/2009/mort2009.csv.zip",
                           destfile = "mort09.zip")
unzip("mort09.zip")
mort09 <- read_csv("mort2009.csv")

mort09 <- mort09 %>%
  filter(ucod %in% c("W32", "W33", "W34")) %>%
  select(restatus, monthdth, sex, age, ager52, ager27, ager12, weekday, year, ucod, race, racer3, racer5)

file.remove("mort2009.csv")
file.remove("mort09.zip")
```

```{r, message = FALSE, include = FALSE, cache = TRUE}
download.file("https://data.nber.org/mortality/2010/mort2010.csv.zip",
                           destfile = "mort10.zip")
unzip("mort10.zip")
mort10 <- read_csv("mort2010.csv")

mort10 <- mort10 %>%
  filter(ucod %in% c("W32", "W33", "W34")) %>%
  select(restatus, monthdth, sex, age, ager52, ager27, ager12, weekday, year, ucod, race, racer3, racer5)

file.remove("mort2010.csv")
file.remove("mort10.zip")
```

```{r, message = FALSE, include = FALSE, cache = TRUE}
download.file("https://data.nber.org/mortality/2011/mort2011.csv.zip",
                           destfile = "mort11.zip")
unzip("mort11.zip")
mort11 <- read_csv("mort2011.csv")

mort11 <- mort11 %>%
  filter(ucod %in% c("W32", "W33", "W34")) %>%
  select(restatus, monthdth, sex, age, ager52, ager27, ager12, weekday, year, ucod, race, racer3, racer5)

file.remove("mort2011.csv")
file.remove("mort11.zip")
```

```{r, message = FALSE, include = FALSE}
download.file("https://data.nber.org/mortality/2012/mort2012.csv.zip",
                           destfile = "mort12.zip")
unzip("mort12.zip")
mort12 <- read_csv("mort2012.csv")

mort12 <- mort12 %>%
  filter(ucod %in% c("W32", "W33", "W34")) %>%
  select(restatus, monthdth, sex, age, ager52, ager27, ager12, weekday, year, ucod, race, racer3, racer5)

file.remove("mort2012.csv")
file.remove("mort12.zip")
```

```{r, message = FALSE, include = FALSE, cache = TRUE}
download.file("https://data.nber.org/mortality/2013/mort2013.csv.zip",
                           destfile = "mort13.zip")
unzip("mort13.zip")
mort13 <- read_csv("mort2013.csv")

mort13 <- mort13 %>%
  filter(ucod %in% c("W32", "W33", "W34")) %>%
  select(restatus, monthdth, sex, age, ager52, ager27, ager12, weekday, year, ucod, race, racer3, racer5)

file.remove("mort2013.csv")
file.remove("mort13.zip")
```

```{r, message = FALSE, include = FALSE, cache = TRUE}
download.file("https://data.nber.org/mortality/2014/mort2014.csv.zip",
                           destfile = "mort14.zip")
unzip("mort14.zip")
mort14 <- read_csv("mort2014.csv")

mort14 <- mort14 %>%
  filter(ucod %in% c("W32", "W33", "W34")) %>%
  select(restatus, monthdth, sex, age, ager52, ager27, ager12, weekday, year, ucod, race, racer3, racer5)

file.remove("mort2014.csv")
file.remove("mort14.zip")
```

```{r, message = FALSE, include = FALSE, cache = TRUE}
download.file("https://data.nber.org/mortality/2015/mort2015.csv.zip",
                           destfile = "mort15.zip")
unzip("mort15.zip")
mort15 <- read_csv("mort2015.csv")

mort15 <- mort15 %>%
  filter(ucod %in% c("W32", "W33", "W34")) %>%
  select(restatus, monthdth, sex, age, ager52, ager27, ager12, weekday, year, ucod, race, racer3, racer5)

file.remove("mort2015.csv")
file.remove("mort15.zip")
```

```{r}
mort0708 <- rbind(mort07, mort08)
mort0709 <- rbind(mort0708, mort09)
mort0710 <- rbind(mort0709, mort10)
mort0711 <- rbind(mort0710, mort11)
mort0712 <- rbind(mort0711, mort12)
mort0713 <- rbind(mort0712, mort13)
mort0714 <- rbind(mort0713, mort14)
allmort <- rbind(mort0714, mort15)
```

```{r}
write_csv(allmort, "mort07-15.csv")
```









